export const dialogues = {
    // Premier duel
    "d1intro": [
        "n Appuye sur Espace pour faire défiler les dialogues.",
        "e Halte étranger!",
        "e Qui es-tu ?",
        "k Je suis Klint.",
        "k Je suis à la recherche d'un criminel prénommé Bad Bill.",
        "e Mmhh, connais pas...",
        "k Et toi, qui es-tu ?",
        "e On me surnomme Old Ben.",
        "e Cette parcelle est mon territoire.",
        "e Personne ne peut y pénétrer.",
        "espit e ...",
        "e Cela ne te pose pas de problème, n'est-ce pas ?",
    ],
    "d1phase2g": [
        "k Je comprends, mais ce chemin est ma seule chance de retrouver Bad Bill.",
        "e Eh bah voyons !",
        "e Et si je refuse qu'est-ce que tu vas faire, hein ?"
    ],
    "d1phase2b": [
        "bad k Si, ça me dérange.",
        "e Tu m'as l'air agressif toi.",
        "e Et si je refuse qu'est-ce que tu vas faire, hein ?"
    ],
    "d1phase3g": [
        "relax k Je ne veux pas d'embrouilles. Laisse-moi simplement passer...",
        "e Mmh, tu sais parler fiston.",
        "idle e Peu importe, je suis persuadé que tu ne sais pas te servir de ton arme.",
        "e T'as vaincu qui toi ? Personne j'imagine ?",
    ],
    "d1phase3b": [
        "bad k Raaaah, je vais t'envoyer six pieds sous terre et passer quand même.",
        "e Sûrement pas !",
        "e J'en ai battu des bien plus costauds que toi, fiston.",
        "e T'as vaincu qui toi ? Personne j'imagine ?",
    ],
    "d1phase4g": [
        "idle k Généralement, j'essaie d'éviter les conflits.",
        "e Sans blague...",
        "espit e ...",
        "e Il faut une première fois à tout alors.",
        "e Allez, affrontons-nous !",
        "n Petit didacticiel avant le combat !",
        "idle show n Voici la jauge de tension.",
        "aug focus n Maintiens Espace lors du combat pour faire monter la jauge.",
        "stop dec relax n Maintiens Majuscule lors du combat pour faire descendre la jauge.",
        "stop jump n Tout au long du combat, la jauge bondira en avant ou en arrière quand l'adversaire se concentrera.",
        "stop idle n Reste le plus longtemps possible dans la zone verte pour désamorcer le combat avec un dialogue.",
        "eidle n Au contraire, rester dans la zone rouge provoquera un tir dans la direction de ton adversaire.",
        "n Attention : si Klint est en colère, il sera plus difficile d'apaiser les tensions.",
        "n Bonne chance !",
    ],
    "d1phase4b": [
        "bad k Je vais commencer par toi, vieux débris !",
        "k Tu me fais perdre mon temps.",
        "e Tu m'as l'air bien trop confiant...",
        "espit e ...",
        "e Voyons ce que tu vaux alors.",
        "e Allez, affrontons-nous !",
        "n Petit didacticiel avant le combat !",
        "idle show n Voici la jauge de tension.",
        "aug focus n Maintiens Espace lors du combat pour faire monter la jauge.",
        "stop dec relax n Maintiens Majuscule lors du combat pour faire descendre la jauge.",
        "stop jump n Tout au long du combat, la jauge bondira en avant ou en arrière quand l'adversaire se concentrera.",
        "stop idle n Reste le plus longtemps possible dans la zone verte pour désamorcer le combat avec un dialogue.",
        "eidle n Au contraire, rester dans la zone rouge provoquera un tir dans la direction de ton adversaire.",
        "n Attention : si Klint est en colère, il sera plus difficile d'apaiser les tensions.",
        "n Bonne chance !",
    ],
    "d1goodend": [
        "k Attends... on n'est pas obligés d'en arriver là.",
        "k Je cherche juste quelqu'un.",
        "k Et se battre ici ne nous apportera rien à tous les deux.",
        "e Mmmmh...",
        "e Beaucoup auraient déjà tiré à ta place.",
        "e Mais t'as raison, les mots… ça vaut parfois plus que le plomb.",
        "e Bon... passe. Mais reste sur tes gardes fiston.",
        "k Merci.",
    ],
    "d1shot": [
        "e ...",
        "e Grr, tu peux passer...",
        "e Voyou !",
        "e Crapule !",
        "e Tu ne vaux pas mieux que celui que tu cherches...",
    ],
    "d1badend": [
        "e Lâche l'affaire fiston. Tu n'fais pas le poids..."
    ],

    // Second duel
    "d2intro": [
        "e Hey, gringo !",
        "e Tu sais où se trouve Rio Bravo ?",
        "k Euh... oui, c'est à un jour de marche vers le nord.",
        "e Vers le nord...",
        "esmile e Bien sûr, je le savais déjà. Je te testais !",
        "efocus e Bon. Maintenant, en garde !",
        "k Attends, tu veux te battre ?",
        "k Mais pourquoi ?",
        "e Pour passer le temps.",
        "eidle e J'éspérai tomber sur quelqu'un d'un peu plus... impressionnant.",
        "e Mais bon, je n'ai rencontré que toi, gringo...",
    ],
    "d2phase2g": [
        "k Je comprends pas pourquoi on se batterait ?",
        "e Parce que...",
        "nreveal esmile e Parce que je suis Ramon El Magnifico !",
        "eflex e Le plus grand duelliste que ce désert n'ait jamais connu.",
    ],
    "d2phase2b": [
        "bad k Moi pas impressionnant ?? Tu sais même pas qui je suis !",
        "eidle e Qui es-tu alors ?",
        "k Je suis Klint.",
        "e C'est bien ce que je pensais, tu n'es personne...",
        "k Gngngn, et toi alors, t'es qui hein ?",
        "nreveal esmile e Je suis Ramon El Magnifico !",
        "eflex e Le plus grand duelliste que ce désert n'ait jamais connu.",
    ],
    "d2phase3g": [
        "k Puisque tu le dis...",
        "relax k Comme tu as l'air sûr de toi, inutile d'en venir aux armes je présume ?",
        "eidle e Mmhh",
        "e Tu es très calme gringo.",
        "idle e Tu me ferais presque douter de mes capacités...",
        "esmile e Mais la seule chose que Ramon El Magnifico sait faire...",
        "efocus e C'est faire parler son revolver !",
    ],
    "d2phase3b": [
        "bad k Non, c'est impossible.",
        "k JE suis le plus grand duelliste que ce désert n'ait jamais connu.",
        "k Je gagnerai les yeux fermés !",
        "idle e C'est ça oui.",
        "e Reste prudent, amigo...",
        "esmile e Si il y a bien une seule chose que Ramon El Magnifico sait faire...",
        "efocus e C'est faire parler son revolver !",
    ],
    "d2phase4g": [
        "idle k Ce n'est pas vrai !",
        "eidle k Tu as probablement d'autres qualités, j'en suis sûr.",
        "esad e Assez, gringo !",
        "e Ramon ne peut prouver sa vraie valeur que par la confrontation.",
        "e Alors, ne m'humilie pas plus...",
        "eidle e Affrontons-nous."
    ],
    "d2phase4b": [
        "bad k Tu parles beaucoup trop, Ramon El Machin...",
        "eidle k Je poursuis quelqu'un alors ne perdons pas plus de temps.",
        "k Tu voulais te battre ?",
        "k Voyons ce que tu vaux alors...",
    ],
    "d2goodend": [
        "k Ça suffit !",
        "k Tu es perdu et tu as soif.",
        "k Si tu acceptes de mettre fin à cet affrontement...",
        "esmile k ...je pourrai te donner à boire et t'indiquer le chemin vers Rio Bravo.",
        "e C'est d'accord, gringo, tu m'as eu..."
    ],
    "d2shot": [
        "k Ah bah tu vois...",
        "k C'est moi le plus grand duelliste !",
        "k File maintenant ...",
    ],
    "d2badend": [
        "e File, gringo. Tu n'es pas digne de rester auprès de Ramon El Magnifico...",
    ],

    // Troisième duel
    "d3intro": [
    "e Hammt-mmh !",
    "k Pardon ?",
    "e Hammt-mmh !",
    "e Ammmte-vmmh tmm dmsmeuhht !",
    "k Je comprends rien !",
    "k Ça serait peut-être mieux sans le cigare...",
    "ermcig e ...",
    "e Vous traversez MON champ pétrolier jeune homme.",
    "e Mon champ. Ma propriété. Mon or noir.",
    "k J'avais besoin de passer, c'est le chemin le plus court.",
    "e Le chemin le plus court... Vous entendez ça ?",
    "e Les gens de votre espèce ne savent donc pas lire les panneaux ?",
],
"d3phase2g": [
    "k Les panneaux étaient tombés...",
    "k Désolé, je veux juste passer, rien de plus.",
    "e Vous... vous vous excusez ? C'est tout ?",
    "e Vous n'avez aucune fierté, ma parole.",
    "e Un vrai gentleman se défendrait...",
    "e ... mais vous n'êtes qu'un vulgaire cowboy.",
    "e Enfin bon. Puisque vous insistez pour jouer les pitoyables...",
    "e Moi, Leviticus Flint, je vais vous faire une proposition :",
    "egivemoney e ez ces quelques dollars et allez voir ailleurs.",
],
"d3phase2b": [
    "bad k Bien sûr que je sais lire !",
    "k Les panneaux étaient tombés...",
    "k Et dans tous les cas, je vais pas m'arrêter juste à cause d'un vieux grincheux.",
    "e Comment osez-vous me parler sur ce ton ?!",
    "e Savez-vous à qui vous vous adressez ?",
    "k À un type en costume qui aime s'entendre parler ?",
    "e Je suis Leviticus Flint !",
    "e Propriétaire de la Flint Oil Company.",
    "e Et je vais vous faire une proposition :",
    "egivemoney e Prenez ces quelques dollars et allez voir ailleurs.",
],
"d3phase3g": [
    "k Je ne suis pas là pour l'argent.",
    "etakemoney k Je suis à la poursuite d'un criminel.",
    "k Il me faut à tout prix passer, mon temps est compté.",
    "e Hors de question !",
    "e Je ne peux me permettre de laisser un homme de votre statut traverser ma propriété.",
],
"d3phase3b": [
    "bad k Garde ton fric, vieux croûton !",
    "etakemoney k J'ai le droit de passer où je veux.",
    "e Le droit ?! Le DROIT ?!",
    "e Je décide de vos droits.",
    "e Et traverser ma propriété n'en fait pas partie.",
],
"d3phase4g": [
    "relax k Écoutez, Monsieur Flint. J'veux pas d'histoires.",
    "k Si vous me laissez passer tranquillement, ça coûte rien à personne.",
    "idle e Vous laisser passer ? Dans MON champ ?",
    "e Ce serait donner raison aux sans-gêne et aux sans-le-sou.",
    "e Non, non et non. Un Flint ne cède pas.",
    "e Si je ne peux vous convaincre avec des dollars ...",
    "e ... je vais devoir vous chasser avec le revolver.",
    "e En garde !",
],
"d3phase4b": [
    "bad k T'es de loin le type le plus agaçant que j'ai jamais rencontré.",
    "e Je suis offensé. Profondément offensé.",
    "e On va régler ça ici et maintenant, cowboy.",
    "k Parfait, je demande que ça.",
    "e En garde !",
],
"d3goodend": [
    "k C'est bon, Flint. Inutile de dégainer.",
    "k Je vous propose un marché : je répare vos panneaux tombés en partant...",
    "k ...et vous me laissez passer sans histoire. Qu'est-ce que vous en dites ?",
    "e C'est... acceptable.",
    "e Mais ne remettez plus les pieds ici, cowboy.",
],
"d3shot": [
    "k Tu pouvais pas m'arrêter, je t'avais prévenu.",
    "k Écarte toi de mon chemin maintenant...",
],
"d3badend": [
    "e Allez, déguerpissez. Et ne revenez JAMAIS sur mes terres.",
    "e Les cowboys errants... Quelle plaie.",
],

    // Arrestation
    "Aintro": [
        "e Klint !",
        "e C'est bien toi, Klint ?",
    ],
    "Aphase2g": [
        "k C'est moi.",
        "k Que me veut-tu ?",
        "e C'est terminé Klint...",
        "e Tu es en état d'arrestation.",
        "e Tu as terrorisé toute la région.",
        "e Tu pousses toutes les personnes que tu as rencontré à t'affronter en duel.",
        "e Il est l'heure de répondre de tes actes.",
    ],
    "Aphase2b": [
        "k Connais pas...",
        "e Ça suffit !",
        "e Je sais qui tu es.",
        "e Tu as terrorisé toute la région.",
        "e Tu pousses toutes les personnes que tu as rencontré à t'affronter en duel.",
        "bad k Quoi ! Mais ...",
        "e Il est l'heure de répondre de tes actes.",
    ],
    "Aphase3g": [
        "relax k Je comprends pas...",
        "k Je suis recherché ?",
        "e Bien vu, cowboy !",
        "e Il fallait peut-être réfléchir un peu plus avant de tirer sur tes adversaires...",
        "e Si tu te rends sans faire d'histoires, je ferai en sorte d'alléger ta peine.",
        "e Qu'en dis-tu ?",
    ],
    "Aphase3b": [
        "bad k Répondre de mes actes ???",
        "k Comme si j'avais quelque chose à me reprocher.",
        "e Ne rends pas la situation plus difficile qu'elle ne l'est déjà...",
        "e Si tu te rends sans faire d'histoires, je ferais en sorte d'alléger ta peine.",
        "e Qu'en dis-tu ?",
    ],
    "Aphase4g": [
        "handsup k C'est d'accord, je me rends.",
        "k C'est vrai que j'aurais pu trouver d'autres solutions pour résoudre ces duels...",
        "e C'est la bonne décision, cowboy.",
        "e Je suis sûre que la justice saura se montrer clémente avec toi...",
    ],
    "Aphase4b": [
        "bad k J'en dis que tu commences à me gonfler !",
        "k Écarte-toi, ou tu subiras le même sort que mes précédents adversaires.",
        "e Bon, tu ne me laisses pas le choix cowboy.",
        "k Voyons ce que tu vaux alors...",
    ],
    "Agoodend": [
        "k C'est bon...",
        "handsup k Tu es plus forte, je me rends.",
        "e Tu fais le bon choix.",
        "e Cette fois, tu n'aurais pas fait le poids...",
    ],
    "Abadend": [
        "e Assez joué cowboy !",
        "e C'est le moment pour toi d'aller faire un séjour au pénitencier...",
    ],

    // Duel final
    "DFintro": [
        "k Bad Bill !",
        "k Enfin te voilà...",
        "e Ça alors...",
        "e Klint, je ne m'attendais pas à te croiser si loin de Rio Bravo.",
        "e Qu'est-ce que tu me veux ?",
    ],
    "DFphase2g": [
        "k Rends-toi, Bad Bill.",
        "k Tu as dévalisé l'épicerie de mes parents...",
        "k Tu dois répondre de tes actes à présent.",
        "good e Comme si j'allais écouter un froussard comme toi !",
        "e Et qu'est-ce que tu comptes faire exactement, hein ?",
        "e Tu ne comptes quand même pas m'affronter ?",
    ],
    "DFphase2b": [
        "bad k Je veux me venger !",
        "k Tu as dévalisé l'épicerie de mes parents...",
        "k Tu vas en payer les conséquences tout de suite.",
        "e Bah voyons...",
        "e Et comment tu comptes t'y prendre, hein ?",
        "e Tu ne comptes quand même pas m'affronter ?",
    ],
    "DFphase3g": [
        "idle k Effectivement, je ne compte pas t'affronter.",
        "k Tu es coupable et tu le sais...",
        "k C'est le moment de te remettre en question.",
        "k Tu ne peux pas continuer à terroriser tout le monde...",
        "good e Raah, mais pour qui tu te prends ?",
        "e N'oublie pas Klint, toi et moi on est différents.",
        "e Tu n'égaleras jamais mes capacités de tireur.",
    ],
    "DFphase3b": [
        "bad k Bien sûr que si que je compte t'affronter !",
        "k Je compte même te battre.",
        "e Ahahaha",
        "e Pauvre Klint...",
        "e Tu es toujours aussi pathétique.",
        "e Ne l'oublie pas, tu ne seras jamais à ma hauteur.",
    ],
    "DFphase4g": [
        "relax k On est pas obligés de tout règler avec les revolvers...",
        "k Je veux simplement que tu t'excuses et que tu rembourses ce que tu as volé.",
        "idle good e La ferme !",
        "e T'es pas en position pour me faire la morale...",
        "k Du calme, Bad Bill...",
        "rage e Mais je suis CALME.",
        "k C'est pas vraiment l'impression que ça donne...",
        "e Assez, tu me gonfles, en garde !",
    ],
    "DFphase4b": [
        "bad k On parie ?",
        "k Je propose qu'on en finisse tout de suite.",
        "k On va voir qui est le plus fort...",
        "k En garde, vaurien !",
    ],
    "DFgoodend": [
        "e Quoi !? Mais qu'est-ce que tu fais ?",
        "e Allez, bats-toi !",
        "k Non.",
        "k J'en ai assez de tous ces combats...",
        "e Lâche !",
        "k La vraie lâcheté, c'est de croire que ton six-coups règlera tous tes problèmes.",
        "k Même si tu gagnes ce combat, tu ne pourras pas échapper aux remords de tes crimes.",
        "k Il est l'heure de prendre un nouveau départ tu ne crois pas ?",
        "reflexion e ...",
        "e ...",
        "e Je ...",
        "rmrage e Je veux juste que les gens arrêtent de me regarder de haut.",
        "e Je pensais que si j'étais la gâchette la plus rapide, on finirait par me respecter...",
        "e ...mais au final je me retrouve souvent tout seul.",
        "rmmask k Ça pourrait changer si tu répares tes torts.",
        "k Alors, on oublie ce duel ?",
        "excited e ... D'accord. On l'oublie.",
    ],
    "DFbadend": [
        "e AHAHA, pitoyable...",
        "e Tu as toujours naïvement pensé que tu étais le héros de l'histoire, hein ?",
        "e File, il vaudrait mieux pour toi que je ne te revois plus jamais...",
    ],
};