export const dialogues = {
    // Premier duel
    "d1intro": [
        "n Appuye sur Espace pour faire défiler les dialogues.",
        "e Halte étranger!",
        "e Qui est-tu ?",
        "k Je suis Klint.",
        "k Je suis à la recherche d'un criminel prénomé Bad Bill.",
        "e Mmhh, connais pas...",
        "k Et toi, qui est-tu ?",
        "e On me surnomme Old Ben.",
        "e Cette parcelle est mon territoire.",
        "e Personne ne peut y pénétrer.",
        "e Cela ne te pose pas de problème, n'est-ce pas ?"
    ],
    "d1phase2g": [
        "k Je comprends, mais ce chemin est ma seule chance de retrouver Bad Bill.",
        "e Eh bah voyons...",
        "e Et si je refuse qu'est-ce que tu va faire, hein ?"
    ],
    "d1phase2b": [
        "bad k Si, ça me dérange.",
        "e Tu m'as l'air agressif toi... Pas cool !",
        "e Et si je refuse qu'est-ce que tu va faire, hein ?"
    ],
    "d1phase3g": [
        "relax k Je ne veux pas d'embrouilles. Laisse-moi simplement passer...",
        "e Mmh, tu sais parler fiston.",
        "idle e Peu importe, je suis persuadé que tu ne sais pas te servir de ton arme.",
        "e T'as vaincu qui toi ? Personne j'imagine ?",
    ],
    "d1phase3b": [
        "bad k Raaaah, je vais t'envoyer six pieds sous terre et passer quand même.",
        "e Sûrement pas !",
        "e J'en ai battu des bien plus costauds que toi, fiston.",
        "e T'as vaincu qui toi ? Personne j'imagine ?",
    ],
    "d1phase4g": [
        "k Généralement, j'essaie d'éviter les conflits.",
        "e Sans blague...",
        "e Il faut une première fois à tout alors.",
        "e Allez, affrontons-nous !",
        "n Le duel va commencer !",
        "focus n Maintiens Espace lors du combat pour utiliser la position de concentration.",
        "relax n Maintiens Shift lors du combat pour utiliser la position de détente.",
        "idle show n Voici la jauge de duel.",
        "n Reste le plus longtemps possible dans la zone verte pour désamorcer le combat avec un dialogue.",
        "n Au contraire, rester dans la zone rouge provoquera un tir dans la direction de ton adversaire.",
        "efocus n Tout au long du combat, l'adversaire tentera d'intimider Klint en adoptant sa position de concentration.",
        "n Appuye sur la touche D au bon moment pour résister à son intimidation.",
        "showi n Les contres réussis seront indiqué par un marqueur vert en dessus de l'ennemi et réduirons considérablement l'influence sur la jauge de duel.", 
        "hidei eidle n Attention : si Klint est en colère, il sera plus difficile d'apaiser les tensions.",
        "n Bonne chance !",
    ],
    "d1phase4b": [
        "bad k Je vais commencer par toi, vieux débris !",
        "k Tu me fais perdre mon temps.",
        "e Tu m'as l'air bien trop confiant...",
        "e Voyons ce que tu vaut alors.",
        "e Allez, affrontons-nous !",
        "n Le duel va commencer !",
        "focus n Maintiens Espace lors du combat pour utiliser la position de concentration.",
        "relax n Maintiens Shift lors du combat pour utiliser la position de détente.",
        "idle show n Voici la jauge de duel.",
        "n Reste le plus longtemps possible dans la zone verte pour désamorcer le combat avec un dialogue.",
        "n Au contraire, rester dans la zone rouge provoquera un tir dans la direction de ton adversaire.",
        "efocus n Tout au long du combat, l'adversaire tentera d'intimider Klint en adoptant sa position de concentration.",
        "n Appuye sur la touche D au bon moment pour résister à son intimidation.",
        "showi n Les contres réussis seront indiqué par un marqueur vert en dessus de l'ennemi et réduirons considérablement l'influence sur la jauge de duel.", 
        "hidei eidle n Attention : si Klint est en colère, il sera plus difficile d'apaiser les tensions.",
        "n Bonne chance !",
    ],
    "d1goodend": [
        "k Attends... on n'est pas obligés d'en arriver là.",
        "k Je cherche juste quelqu'un.",
        "k Et se battre ici ne nous apportera rien à tous les deux.",
        "e Mmmmh...",
        "e Beaucoup auraient déjà tiré à ta place.",
        "e Mais t'as raison, les mots… ça vaut parfois plus que le plomb.",
        "e Bon... passe. Mais reste sur tes gardes fiston.",
        "k Merci.",
    ],
    "d1badend": [
        "e Lâche l'affaire fiston. Tu n'fais pas le poids..."
    ],

    // Second duel
    "d2intro": [
        "e Hey, toi !",
        "e Tu sais où se trouve Rio Bravo ?",
        "k Euh... oui, c'est à un jour de marche vers le nord.",
        "e Vers le nord...",
        "e Bien sûr, je le savais déjà. Je te testais.",
        "e Bon. Maintenant, en garde !",
        "k Attends, tu veux te battre ?",
        "k Mais pourquoi ?",
        "e Pour passer le temps.",
        "e J'éspérais tomber sur quelqu'un d'un peu plus... impressionant.",
        "e Mais bon, je n'ai rencontré que toi gringo...",
    ],
    "d2phase2g": [
        "k Je comprends pas pourquoi on se batterait ?",
        "e Parce que...",
        "e Parce que je suis Ramon El Magnifico !",
        "e Le plus grand duelliste que ce désert n'ait jamais connu.",
    ],
    "d2phase2b": [
        "bad k Moi pas impressionant ?? Tu sais même pas qui je suis !",
        "e Qui es-tu alors ?",
        "k Je suis Klint.",
        "e C'est bien ce que je pensais, tu n'es personne...",
        "k Gngngn, et toi alors, t'es qui hein ?",
        "e Je suis Ramon El Magnifico !",
        "e Le plus grand duelliste que ce désert n'ait jamais connu.",
    ],
    "d2phase3g": [
        "k Puisque tu le dis...",
        "relax k Comme tu as l'air sûr de toi, inutile d'en venir aux armes je présume ?",
        "e Mmhh",
        "e Tu es très calme gringo.",
        "idle e Tu me ferais presque douter de mes capacités...",
        "e Mais la seule chose que Ramon El Magnifico sait faire...",
        "e C'est faire parler son revolver !",
    ],
    "d2phase3b": [
        "bad k Non, c'est impossible.",
        "k JE suis le plus grand duelliste que ce désert n'ait jamais connu.",
        "k Je gagnerais les yeux fermés !",
        "e C'est ça oui.",
        "e Reste prudent, amigo...",
        "e Si il y a bien une seule chose que Ramon El Magnifico sait faire...",
        "e C'est faire parler son revolver !",
    ],
    "d2phase4g": [
        "k Ce n'est pas vrai !",
        "k Tu as probablement d'autres qualités, j'en suis sûr.",
        "e Assez, gringo !",
        "e Ramon ne peut prouver sa vrai valeur que par la confrontation.",
        "e Alors, ne m'humilie pas plus...",
        "e Affrontons-nous."
    ],
    "d2phase4b": [
        "bad k Tu parles beaucoup trop, Ramon El Machin...",
        "k Je poursuis quelqu'un alors ne perdons pas plus de temps.",
        "k Tu voulais te battre ?",
        "k Voyons ce que tu vaut alors...",
    ],
    "d2goodend": [
        "k Ça suffit !",
        "k Tu est perdu et tu as soif.",
        "k Si tu acceptes de mettre fin à cet affrontement...",
        "k ...je pourrai te donner à boire et t'indiquer le chemin vers Rio Bravo.",
        "e C'est d'accord, gringo, tu m'as eu..."
    ],
    "d2badend": [
        "e ",
    ],
};